

//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------


namespace Asp.net_Exercise.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class DatabaseEntities : DbContext
{
    public DatabaseEntities()
        : base("name=DatabaseEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Color> Color { get; set; }

    public virtual DbSet<Img> Img { get; set; }

    public virtual DbSet<Keep> Keep { get; set; }

    public virtual DbSet<Member> Member { get; set; }

    public virtual DbSet<Member_Store> Member_Store { get; set; }

    public virtual DbSet<Order> Order { get; set; }

    public virtual DbSet<OrderDetail> OrderDetail { get; set; }

    public virtual DbSet<Prod_Img> Prod_Img { get; set; }

    public virtual DbSet<Prod_Type> Prod_Type { get; set; }

    public virtual DbSet<ProdFeature> ProdFeature { get; set; }

    public virtual DbSet<Quantity> Quantity { get; set; }

    public virtual DbSet<ShoppingCar> ShoppingCar { get; set; }

    public virtual DbSet<Size> Size { get; set; }

    public virtual DbSet<Store> Store { get; set; }

    public virtual DbSet<Type> Type { get; set; }

    public virtual DbSet<Product> Product { get; set; }

}

}

